# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 18:26
from __future__ import unicode_literals

import Companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('licence_type', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('days_remaining', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
                ('truck_num', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'verbose_name_plural': 'notifications',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=14)),
                ('insurance_number', models.PositiveIntegerField()),
                ('insurance_expiry', models.DateField()),
                ('fitness_certificate_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fitness_certificate_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Companies.models.upload_image_path)),
            ],
        ),
    ]
