# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='fitness_certificate_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fitness_certificate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
