# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='truck_num',
        ),
        migrations.AddField(
            model_name='notification',
            name='truck',
            field=models.CharField(default=21, max_length=14),
        ),
    ]
