# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 08:43
from __future__ import unicode_literals

import Companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_auto_20180207_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Companies.models.upload_image_path),
        ),
    ]
