# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_truck_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField()),
                ('compan_name', models.CharField(max_length=80)),
                ('licence_type', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('days_remaining', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
            ],
            options={
                'verbose_name_plural': 'notifications',
                'ordering': ['-created'],
            },
        ),
    ]
