# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_notification_truck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='fitness_certificate_expiry',
            field=models.DateField(default=None),
        ),
    ]
