# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='compan_name',
            new_name='company_name',
        ),
    ]
